### ISSUE TITLE
Cannot find "OnlineTfidfDocRanker" 

### ISSUE THREAD

**Issue by nayeon7lee** [sheffieldnlp/fever-baselines#37]
Hi, 
Inside the "process_tfidf_drqa.py" file, there is a line trying to import OnlineTfidfDocRanker (i.e. "from drqascripts.retriever.build_tfidf_lines import OnlineTfidfDocRanker"), however, i cannot locate this file within the provided codebase. Can I know where i can find this file?

**Comment by j6mes** [comment]
Hi, did all the dependencies install OK when you ran `pip install -r requirements.txt`?

I have updated some of those recently might be worth upgrading the dependencies again: `pip install --upgrade -r requirements.txt` (or maybe with `--force` if needs be).

J

**Comment by nayeon7lee** [comment]
It works now. Thanks a lot for your help!

**Comment by j6mes** [comment]
np

**Comment by chiphuyen** [comment]
The issue didn't resolve for me after I've run the upgrade.

**Comment by j6mes** [comment]
The Online Ranker is something I've added to a fork of DrQA - so it wouldn't be in the original code base. In the requirements.txt file, it points to my own fork.

Are you still having issues?
