### ISSUE TITLE
ImportError: cannot import name 'Dataset'

### ISSUE THREAD

**Issue by chiphuyen** [sheffieldnlp/fever-baselines#39]
When I trained the Decomposable Attention model, I got the bug:
```
File "src/scripts/rte/da/train_da.py", line 9, in <module>
    from allennlp.data import Vocabulary, Dataset, DataIterator, DatasetReader, Tokenizer, TokenIndexer
ImportError: cannot import name 'Dataset'
```

I installed allennlp from source and when I looked into the folder data, there's nothing called Dataset. Does anybody know how to fix this problem? Thanks!

**Comment by j6mes** [comment]
Hi, if you're installing allennlp from source, you'd need to select version 0.2.3 as I think in later versions, they cease to use the Dataset class.

I'd recommend using pip to manage the dependencies.

Hope this helps

**Comment by chiphuyen** [comment]
When I tried to install via pip3 allennlp==0.2.3, I kept getting this message:
```
sanic-plugins-framework 0.5.2.dev20180201 has requirement sanic>=0.7.0, but you'll have sanic 0.6.0 which is incompatible.
sanic-cors 0.9.4 has requirement sanic>=0.7.0, but you'll have sanic 0.6.0 which is incompatible.
Installing collected packages: sanic-plugins-framework, sanic-cors
Successfully installed sanic-cors-0.9.4 sanic-plugins-framework-0.5.2.dev20180201
```
I looked into the setup.py and see the required packages are:
```
 install_requires=[
          'pyhocon==0.3.35',
          'typing',
          'overrides',
          'nltk',
          'spacy',
          'numpy',
          'pillow',
          'tensorboard-pytorch',
          'cffi==1.11.2',
          'awscli>=1.11.91',
          'sanic==0.6.0',
          'sanic-cors',
          'argparse',
          'requests>=2.18',
          'tqdm',
          'editdistance',
          'jupyter'
      ]
```
Apparently, the newest version of sanic-cors conflits with sanic==0.6.0. Does anyone know how to fix this problem? Thanks a lot!

**Comment by j6mes** [comment]
Hi Chip,

Yes, DrQA and AllenNLP have conflicting packages - this isn't an issue as I don't use spacy or sanic in this implantation.

I think the issue is that I didn't specify the PyTorch version in the instructions. It must be 0.3.1 (which was latest at time of publication) - the latest version introduces breaking changes).

I've updated the instructions and re-ran the setup and it works for me.

Note that this is not designed to run on Windows OSs. 

Hope this helps - James

**Comment by shubhamitradas** [comment]
Hi James ,
Facing this issue 👍 
ImportError: cannot import name 'Dataset'

with PyTorch 0.4.0 and allennlp installed with pip command.
As per the previous comment, uninstalled PyTorch 0.4.0 and install PyTorch 0.3.1 but getting  the following error now : 

AttributeError                            Traceback (most recent call last)
<ipython-input-1-8ff68cd92fd3> in <module>()
     12 from allennlp.common import Params
     13 from allennlp.common.checks import ConfigurationError
---> 14 from allennlp.data import DatasetReader, Dataset, Instance
     15 from allennlp.data.fields import TextField, LabelField, ListField
     16 from allennlp.data.tokenizers import Tokenizer, WordTokenizer

/usr/local/lib/python3.6/dist-packages/allennlp/data/__init__.py in <module>()
----> 1 from allennlp.data.dataset_readers.dataset_reader import DatasetReader
      2 from allennlp.data.fields.field import DataArray, Field
      3 from allennlp.data.instance import Instance
      4 from allennlp.data.iterators.data_iterator import DataIterator
      5 from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType

/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset_readers/__init__.py in <module>()
      8 
      9 # pylint: disable=line-too-long
---> 10 from allennlp.data.dataset_readers.conll2003 import Conll2003DatasetReader
     11 from allennlp.data.dataset_readers.coreference_resolution import ConllCorefReader, WinobiasReader
     12 from allennlp.data.dataset_readers.dataset_reader import DatasetReader

/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset_readers/conll2003.py in <module>()
      8 from allennlp.common.checks import ConfigurationError
      9 from allennlp.common.file_utils import cached_path
---> 10 from allennlp.data.dataset_readers.dataset_reader import DatasetReader
     11 from allennlp.data.dataset_readers.dataset_utils import iob1_to_bioul
     12 from allennlp.data.fields import TextField, SequenceLabelField, Field

/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset_readers/dataset_reader.py in <module>()
      2 import logging
      3 
----> 4 from allennlp.data.instance import Instance
      5 from allennlp.common import Params, Tqdm
      6 from allennlp.common.checks import ConfigurationError

/usr/local/lib/python3.6/dist-packages/allennlp/data/instance.py in <module>()
      1 from typing import Dict, Mapping
      2 
----> 3 from allennlp.data.fields.field import DataArray, Field
      4 from allennlp.data.vocabulary import Vocabulary
      5 

/usr/local/lib/python3.6/dist-packages/allennlp/data/fields/__init__.py in <module>()
      7 from allennlp.data.fields.array_field import ArrayField
      8 from allennlp.data.fields.index_field import IndexField
----> 9 from allennlp.data.fields.knowledge_graph_field import KnowledgeGraphField
     10 from allennlp.data.fields.label_field import LabelField
     11 from allennlp.data.fields.multilabel_field import MultiLabelField

/usr/local/lib/python3.6/dist-packages/allennlp/data/fields/knowledge_graph_field.py in <module>()
     15 from allennlp.data.tokenizers.tokenizer import Tokenizer
     16 from allennlp.data.vocabulary import Vocabulary
---> 17 from allennlp.nn import util as nn_util
     18 from allennlp.semparse.contexts.knowledge_graph import KnowledgeGraph
     19 

/usr/local/lib/python3.6/dist-packages/allennlp/nn/__init__.py in <module>()
      1 from allennlp.nn.activations import Activation
----> 2 from allennlp.nn.initializers import Initializer, InitializerApplicator
      3 from allennlp.nn.regularizers import RegularizerApplicator

/usr/local/lib/python3.6/dist-packages/allennlp/nn/initializers.py in <module>()
    165 # There are no classes to decorate, so we hack these into Registrable._registry
    166 Registrable._registry[Initializer] = {  # pylint: disable=protected-access
--> 167         "normal": _initializer_wrapper(torch.nn.init.normal_),
    168         "uniform": _initializer_wrapper(torch.nn.init.uniform_),
    169         "orthogonal": _initializer_wrapper(torch.nn.init.orthogonal_),

AttributeError: module 'torch.nn.init' has no attribute 'normal_'.

FYI ,I am trying out in Google Colab.
