### ISSUE TITLE
NameError: name 'get_count_matrix' is not defined

### ISSUE THREAD

**Issue by maxsonate** [sheffieldnlp/fever-baselines#41]
I see this after cloning the latest version. 
Traceback (most recent call last):
  File "src/scripts/build_tfidf.py", line 34, in <module>
    count_matrix, doc_dict = get_count_matrix(
NameError: name 'get_count_matrix' is not defined
Looking at drqascripts.retriever.build_tfidf:
  class TfIdfBuilder(builtins.object): 
 get_count_matrix(self)

But it's called as a static class in src/scripts/build_tfidf.py

**Comment by j6mes** [comment]
Thanks for reporting it. It's a slight oversight on my part. I had to rewrite part of DrQA to make it thread-safe when running in parallel for the IR part of the script.

Just pushed the latest change to `v0.2`
 
J
