### ISSUE TITLE
installation fails with pip 10.0.1

### ISSUE THREAD

**Issue by maxsonate** [sheffieldnlp/fever-baselines#43]
Building wheels for collected packages: drqa, fever-scorer, drqa, fever-scorer
  Running setup.py bdist_wheel for drqa ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-cfhla23v/wheels/25/a8/71/6390f88d8b3ecda4c32998985670851ed7281bfa8ced27196e
  Running setup.py bdist_wheel for fever-scorer ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-cfhla23v/wheels/e0/c6/1a/8ff7f96802122bf337bfc8e05852f7d5618a6cffc95b5ee624
  Running setup.py bdist_wheel for drqa ... error
  Complete output from command /home/ubuntu/anaconda3/envs/fever/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnfl6_v5/drqa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-5hao0iio --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/anaconda3/envs/fever/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vnfl6_v5/drqa/setup.py'
  
  ----------------------------------------
  Failed building wheel for drqa
  Running setup.py clean for drqa
  Complete output from command /home/ubuntu/anaconda3/envs/fever/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnfl6_v5/drqa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/anaconda3/envs/fever/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vnfl6_v5/drqa/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for drqa
  Running setup.py bdist_wheel for fever-scorer ... error
  Complete output from command /home/ubuntu/anaconda3/envs/fever/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnfl6_v5/fever-scorer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3rmxr6dz --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/anaconda3/envs/fever/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vnfl6_v5/fever-scorer/setup.py'
  
  ----------------------------------------
  Failed building wheel for fever-scorer
  Running setup.py clean for fever-scorer
  Complete output from command /home/ubuntu/anaconda3/envs/fever/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnfl6_v5/fever-scorer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/anaconda3/envs/fever/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vnfl6_v5/fever-scorer/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for fever-scorer

**Comment by maxsonate** [comment]
It works with pip 9.0.1 though

**Comment by j6mes** [comment]
Looks like it's an undocumented feature with pip with VCS builds: https://github.com/pypa/pip/issues/3055

I've found that removing the egg info from the requirements.txt fixes it... for now. Will be pushing the changes shortly

James.
